baseURL = 'https://flo-leetcode.github.io'
languageCode = 'en-us'
title = 'Flo Leetcode 算法营 Blog'
theme= 'PaperMod'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[services]
  [services.disqus]
    shortname = 'disqus_16Z9akCcbJ'
[params]
  comments = true
  